### PR TITLE
WIP Fixes lots of bugs

### PR DESCRIPTION
**Pull request by KyrneDev**
As per #16 we need to fix several things, this PR is those fixes

- [x] #15 - Firefox issues
- [x] #12 - Reactions conflict
- [x] #20 - Edit poll problem
- [x] #9 - i18n
- [x] #19 - Improve style of polls

### CODE REVIEW

**Comment by KyrneDev** [comment]
PR is finished, awaiting code review

**Comment by ghost** [comment]
@CDK2020 Do you have some screenshots?

**Comment by KyrneDev** [comment]
@PartialDevAdmin 

https://imgur.com/a/qmlgJB0

**Comment by ghost** [comment]
@CDK2020 I am unable to access imgur, can you share an image directly?

**Comment by dsevillamartin** [comment]
@PartialDevAdmin 
img

**Comment by ghost** [comment]
@datitisev Looks good! I am going to clone the repo locally and test it out, will report back then!

**Comment by dsevillamartin** [comment]
- Fixed percentage number disappearing if background width is > 0%
- Calculate inverted colors with less (uses css variables, [not supported in IE but who cares](https://caniuse.com/#feat=css-variables))
- Moved some CSS around
- Some other stuff... I have forgotten already

**Review by dsevillamartin — APPROVED** [review]
Looks good after my great changes 🙂😁

**Pull request merged**
